apiVersion: v1
kind: Service
metadata:
  name: # 🔍 choose a name for your service
spec:
  type: NodePort
  selector:
    app: # 🔍 must match the Pod label exactly
  ports:
    - port: # 🔍 service port (match your app)
      targetPort: # 🔍 where the app listens inside the container
      nodePort: # 🔍 expose this service on a high port (30000–32767)
